### ISSUE TITLE
Write Unit Tests for useCardFlip Hook

### ISSUE THREAD

**Issue by ShavonHarris-Dev** [ShavonHarris-Dev/go-fish-date-night#3]
## Description

We need to write unit tests for the `useCardFlip` custom hook to ensure its functionality is working as expected.

## Tasks

- [ ] Write tests to ensure `flippedCards` is an empty array initially.
- [ ] Write tests for the `flipCard` function to ensure it adds the index to `flippedCards` when less than 2 cards are flipped and the card is not already flipped.
- [ ] Write tests for the `unflipCards` function to ensure it empties the `flippedCards` array.
- [ ] Write tests for the `checkMatch` function to ensure it sets `match` to true when two flipped cards match and calls `unflipCards` after a delay when they don't.
- [ ] Write tests to ensure `checkMatch` is called when two cards are flipped.

## Acceptance Criteria

- All tests pass successfully.
- Each function in `useCardFlip` has at least one corresponding test.
- The tests cover all possible edge cases.
